### ISSUE TITLE
Concatenate Plugins

### ISSUE THREAD

**Issue by dschick** [jkotan/lavue#701]
Hi,

we cannot survive without using LaVue in our lab, and we just started to use the Angle/Q-Plugin.

In this context, we would love to also have some ROIs in this plugin.
Instead of extending this one plugin, wouldn't it be more elegant to concatenate multiple macros somehow?
So that the ROI macro is working on the result of the Angle/Q-plugin?

Best

Daniel

**Comment by jkotan** [comment]
Hi @dschick,

unfortunately, there is no easy way concatenate specialized tools like Angle/Q and ROIs because their functionalities may interfere, e.g. if you switch in Angle/Q to polar-q or polar-th the roi boxes are no more rectangles which is not supported by the ROI tool. 
Sometime ago we had a similar request from one of our beamlines and therefore we created Q+ROI+Proj tool
where you have roi boxes and you can see  q-space coordinates of pixels together.
If you have an idea what could be added to this tool to help you let me know.

Best,

Jan

**Comment by dschick** [comment]
Hi Jan,

thanks for the prompt reply.

> if you switch in Angle/Q to polar-q or polar-th the roi boxes are no more rectangles which is not supported by the ROI tool.

you got a point! indeed a pixel in polar-q plot is not equivalent to a pixel in the original image. But if you map your camera pixels into polar-q space you could map it again onto an according mesh with equidistant spacing.

But of course this might be just one solution for one specific situation and it will be hard to fetch all the different possibilities.

I will give the Q+ROI+Proj tool a try and will reopen this issue in case it is necessary or I have an good idea
